# Example configuration file for AWS Pipeline Watcher
# This file will be automatically created at ~/.config/pipeline-watcher/config.yml

# Option 1: Use AWS CLI credentials with SSO (recommended)
# The tool will automatically detect your AWS CLI configuration and refresh tokens
use_aws_cli: true
aws_profile: default # or specify your profile name
aws_region: us-east-1
aws_account_id: "123456789012" # auto-detected from AWS CLI

# Option 2: Manual AWS credentials (alternative)
# aws_access_key_id: YOUR_AWS_ACCESS_KEY_ID
# aws_secret_access_key: YOUR_AWS_SECRET_ACCESS_KEY
# use_aws_cli: false

# List of pipeline names to monitor
pipeline_names:
  - my-web-app-pipeline
  - api-service-pipeline
  - database-migration-pipeline
  - frontend-deployment

# List of CodeBuild project names to monitor
codebuild_project_names:
  - my-web-app-build
  - api-service-build
  - unit-test-runner
  - integration-tests
# Advanced options (optional)
# sso_session: my-sso-session # For AWS SSO sessions
# refresh_interval: 1800 # Token refresh check interval in seconds (default: 30 minutes)
